// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package uiDisplay

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

const (
	HeaderIconPositionLeft string = "left"
	HeaderIconPositionTop  string = "top"

	HeaderIconBorderRadiusNone string = "none"
	HeaderIconBorderRadiusXs   string = "xs"
	HeaderIconBorderRadiusSm   string = "sm"
	HeaderIconBorderRadiusMd   string = "md"
	HeaderIconBorderRadiusLg   string = "lg"
	HeaderIconBorderRadiusXl   string = "xl"

	HeaderIconPaddingSizeNone string = "none"
	HeaderIconPaddingSizeXs   string = "xs"
	HeaderIconPaddingSizeSm   string = "sm"
	HeaderIconPaddingSizeMd   string = "md"
	HeaderIconPaddingSizeLg   string = "lg"
	HeaderIconPaddingSizeXl   string = "xl"
)

type HeaderIconSettings struct {
	Name string

	// OptionalFields
	BackgroundColor string
	BorderRadius    string
	Color           string
	PaddingSize     string
}

func HeaderIcon(componentSettings HeaderIconSettings) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		iconChipClasses := "ph-duotone inline-flex leading-none items-center justify-center " + componentSettings.Name
		if componentSettings.Color != "" {
			iconChipClasses += " text-" + componentSettings.Color
		}
		if componentSettings.BackgroundColor != "" {
			iconChipClasses += " bg-" + componentSettings.BackgroundColor
		}
		switch componentSettings.PaddingSize {
		case HeaderIconPaddingSizeNone:
			iconChipClasses += " p-0"
		case HeaderIconPaddingSizeXs:
			iconChipClasses += " p-1"
		case HeaderIconPaddingSizeSm:
			iconChipClasses += " p-1.5"
		case HeaderIconPaddingSizeMd:
			iconChipClasses += " p-2"
		case HeaderIconPaddingSizeLg:
			iconChipClasses += " p-2.5"
		case HeaderIconPaddingSizeXl:
			iconChipClasses += " p-3"
		}
		switch componentSettings.BorderRadius {
		case HeaderIconBorderRadiusNone:
			iconChipClasses += " rounded-none"
		case HeaderIconBorderRadiusXs:
			iconChipClasses += " rounded-xs"
		case HeaderIconBorderRadiusSm:
			iconChipClasses += " rounded-sm"
		case HeaderIconBorderRadiusMd:
			iconChipClasses += " rounded"
		case HeaderIconBorderRadiusLg:
			iconChipClasses += " rounded-lg"
		case HeaderIconBorderRadiusXl:
			iconChipClasses += " rounded-xl"
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<!-- HeaderIcon -->")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 = []any{iconChipClasses}
		templ_7745c5c3_Err = templ.RenderCSSItems(ctx, templ_7745c5c3_Buffer, templ_7745c5c3_Var2...)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<i class=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var3 string
		templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.ResolveAttributeValue(templ.CSSClasses(templ_7745c5c3_Var2).String())
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `src/display/headerIcon.templ`, Line: 1, Col: 0}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var3)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "\"></i>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
