// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1070
package uiForm

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	_ "embed"
	"fmt"
	"sync/atomic"

	uiControl "github.com/goinfinite/ui/src/control"
	uiToolset "github.com/goinfinite/ui/src/toolset"
)

//go:embed passwordInputState.js
var passwordInputAlpineState string

var passwordInputAlpineStateOnce = templ.NewOnceHandle(
	templ.WithComponent(uiToolset.MinifierTemplateJs(&passwordInputAlpineState)),
)

var passwordInputRulesScriptIdCounter atomic.Uint64

func generatePasswordInputRulesScriptId() string {
	return fmt.Sprintf(
		"password-input-rules-%d", passwordInputRulesScriptIdCounter.Add(1),
	)
}

type PasswordInputRules struct {
	MinLength                   uint
	MaxLength                   uint
	GenerationLength            uint
	ShouldIncludeLowercaseChars bool
	ShouldIncludeUppercaseChars bool
	ShouldIncludeNumbers        bool
	ShouldIncludeSpecialChars   bool
}

type passwordInputRulesConfig struct {
	MinLength           uint `json:"minLength"`
	MaxLength           uint `json:"maxLength"`
	Length              uint `json:"length"`
	IncludeLowercase    bool `json:"includeLowercase"`
	IncludeUppercase    bool `json:"includeUppercase"`
	IncludeNumbers      bool `json:"includeNumbers"`
	IncludeSpecialChars bool `json:"includeSpecialChars"`
}

type passwordStrengthCriteriaItem struct {
	StateKey string
	Label    string
}

func passwordInputRulesResolver(rules PasswordInputRules) passwordInputRulesConfig {
	config := passwordInputRulesConfig{
		MinLength:           rules.MinLength,
		MaxLength:           rules.MaxLength,
		Length:              rules.GenerationLength,
		IncludeLowercase:    rules.ShouldIncludeLowercaseChars,
		IncludeUppercase:    rules.ShouldIncludeUppercaseChars,
		IncludeNumbers:      rules.ShouldIncludeNumbers,
		IncludeSpecialChars: rules.ShouldIncludeSpecialChars,
	}
	if config.MinLength == 0 {
		config.MinLength = 6
	}
	if config.MaxLength == 0 {
		config.MaxLength = 64
	}
	if config.MaxLength < config.MinLength {
		config.MaxLength = config.MinLength
	}
	if config.Length == 0 {
		config.Length = 16
	}
	if !config.IncludeLowercase && !config.IncludeUppercase &&
		!config.IncludeNumbers && !config.IncludeSpecialChars {
		config.IncludeLowercase = true
		config.IncludeUppercase = true
		config.IncludeNumbers = true
		config.IncludeSpecialChars = true
	}
	return config
}

func passwordStrengthCriteriaItemsResolver(
	config passwordInputRulesConfig,
) []passwordStrengthCriteriaItem {
	criteriaItems := []passwordStrengthCriteriaItem{
		{
			StateKey: "isLongEnough",
			Label: fmt.Sprintf(
				"Between %d and %d characters", config.MinLength, config.MaxLength,
			),
		},
	}
	if config.IncludeNumbers {
		criteriaItems = append(criteriaItems, passwordStrengthCriteriaItem{
			StateKey: "hasNumbers",
			Label:    "At least 1 number",
		})
	}
	if config.IncludeUppercase {
		criteriaItems = append(criteriaItems, passwordStrengthCriteriaItem{
			StateKey: "hasUppercaseChars",
			Label:    "At least 1 uppercase letter",
		})
	}
	if config.IncludeLowercase {
		criteriaItems = append(criteriaItems, passwordStrengthCriteriaItem{
			StateKey: "hasLowercaseChars",
			Label:    "At least 1 lowercase letter",
		})
	}
	if config.IncludeSpecialChars {
		criteriaItems = append(criteriaItems, passwordStrengthCriteriaItem{
			StateKey: "hasSpecialChars",
			Label:    "At least 1 special character",
		})
	}
	return criteriaItems
}

type PasswordInputSettings struct {
	InputName       string
	Label           string
	TwoWayStatePath string

	// OptionalFields
	Rules                                PasswordInputRules
	Value                                string
	Size                                 string
	TextCase                             string
	ActionButtonStyle                    string
	IsRequired                           bool
	IsReadOnly                           bool
	ShouldShowGenerateButton             bool
	ShouldShowStrengthMeter              bool
	StrengthMeterColor                   string
	StrengthCriteriaTextColor            string
	StrengthCriteriaFulfilledIconColor   string
	StrengthCriteriaUnfulfilledIconColor string
	HintValue                            string
	HintStatePath                        string
	HintDisplay                          string
	HintDisplayTooltipBackgroundColor    string
	HintDisplayTooltipMinWidthClass      string
	HintDisplayTooltipMaxWidthClass      string
	HintDisplayTooltipMinHeightClass     string
	HintDisplayTooltipMaxHeightClass     string
	HintIconStyle                        string
}

type passwordInputActionButtonStyle struct {
	BackgroundColor      string
	BackgroundColorHover string
	RingColor            string
	RingColorHover       string
}

type passwordInputActionButtonSize struct {
	ButtonSize     string
	MinWidthClass  string
	MinHeightClass string
}

const (
	PasswordInputActionButtonStyleBoxed string = "boxed"
	PasswordInputActionButtonStylePlain string = "plain"
)

func passwordInputActionButtonStyleResolver(actionButtonStyle string) passwordInputActionButtonStyle {
	if actionButtonStyle == PasswordInputActionButtonStylePlain {
		return passwordInputActionButtonStyle{
			BackgroundColor:      "transparent",
			BackgroundColorHover: "neutral-50/5",
		}
	}
	return passwordInputActionButtonStyle{
		BackgroundColor:      "neutral-50/5",
		BackgroundColorHover: "neutral-50/20",
		RingColor:            "neutral-50/5",
		RingColorHover:       "neutral-50/30",
	}
}

func passwordInputActionButtonSizeResolver(size string) passwordInputActionButtonSize {
	switch size {
	case InputFieldSizeXs:
		return passwordInputActionButtonSize{ButtonSize: uiControl.ButtonSizeXs, MinWidthClass: "min-w-5", MinHeightClass: "min-h-5"}
	case InputFieldSizeSm:
		return passwordInputActionButtonSize{ButtonSize: uiControl.ButtonSizeSm, MinWidthClass: "min-w-6", MinHeightClass: "min-h-6"}
	case InputFieldSizeLg:
		return passwordInputActionButtonSize{ButtonSize: uiControl.ButtonSizeLg, MinWidthClass: "min-w-8", MinHeightClass: "min-h-8"}
	case InputFieldSizeXl:
		return passwordInputActionButtonSize{ButtonSize: uiControl.ButtonSizeXl, MinWidthClass: "min-w-9", MinHeightClass: "min-h-9"}
	}
	return passwordInputActionButtonSize{ButtonSize: uiControl.ButtonSizeMd, MinWidthClass: "min-w-7", MinHeightClass: "min-h-7"}
}

func passwordInputActionButtonSettingsResolver(
	size, actionButtonStyle, ariaLabel, icon, onClickFunc, tooltipContent string,
) uiControl.ButtonSettings {
	actionStyle := passwordInputActionButtonStyleResolver(actionButtonStyle)
	actionSize := passwordInputActionButtonSizeResolver(size)
	return uiControl.ButtonSettings{
		AriaLabel:            ariaLabel,
		BackgroundColor:      actionStyle.BackgroundColor,
		BackgroundColorHover: actionStyle.BackgroundColorHover,
		IconLeft:             icon,
		MinHeightClass:       actionSize.MinHeightClass,
		MinWidthClass:        actionSize.MinWidthClass,
		OnClickFunc:          onClickFunc,
		PaddingSize:          uiToolset.PaddingSizeNone,
		RingColor:            actionStyle.RingColor,
		RingColorHover:       actionStyle.RingColorHover,
		RingThickness:        uiToolset.RingThicknessXs,
		Size:                 actionSize.ButtonSize,
		TextColor:            "neutral-100",
		TextColorHover:       "neutral-100",
		TooltipContent:       tooltipContent,
	}
}

func passwordInputActions(shouldShowGenerateButton bool, passwordStatePath, size, actionButtonStyle string) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		revealButtonSettings := passwordInputActionButtonSettingsResolver(
			size, actionButtonStyle, "", "", "isPasswordVisible = !isPasswordVisible",
			"show/hide the password",
		)
		revealButtonSettings.AriaLabelOneWayStatePath = "isPasswordVisible ? 'Hide password' : 'Show password'"
		revealButtonSettings.IconLeftOneWayStatePath = "isPasswordVisible ? 'ph-eye-slash' : 'ph-eye'"
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"flex shrink-0 items-center gap-1 pr-1 text-neutral-400\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = uiControl.Button(revealButtonSettings).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if shouldShowGenerateButton {
			templ_7745c5c3_Err = uiControl.Button(passwordInputActionButtonSettingsResolver(
				size, actionButtonStyle, "Generate random password", "ph-binary",
				passwordStatePath+" = generateRandomPassword(); copyPasswordToClipboard("+passwordStatePath+")",
				"generate random password",
			)).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "</div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func PasswordInput(componentSettings PasswordInputSettings) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var2 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var2 == nil {
			templ_7745c5c3_Var2 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "<!-- PasswordInput -->")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = passwordInputAlpineStateOnce.Once().Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		rulesConfig := passwordInputRulesResolver(componentSettings.Rules)
		criteriaItems := passwordStrengthCriteriaItemsResolver(rulesConfig)
		rulesScriptId := generatePasswordInputRulesScriptId()
		templ_7745c5c3_Err = templ.JSONScript(rulesScriptId, rulesConfig).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		shouldShowStrengthCriteria := "(" + componentSettings.TwoWayStatePath + " ?? '').length > 0"
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "<div class=\"flex w-full flex-col gap-2\" x-data=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var3 string
		templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.ResolveAttributeValue(templ.JSFuncCall("passwordInput", rulesScriptId))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `src/form/passwordInput.templ`, Line: 254, Col: 59}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var3)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "\" x-effect=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var4 string
		templ_7745c5c3_Var4, templ_7745c5c3_Err = templ.ResolveAttributeValue("updatePasswordStrength(" + componentSettings.TwoWayStatePath + ")")
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `src/form/passwordInput.templ`, Line: 255, Col: 80}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var4)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, "\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = InputField(InputFieldSettings{
			InputType:           InputTypePassword,
			InputTypeExpression: "isPasswordVisible ? 'text' : 'password'",
			InputName:           componentSettings.InputName,
			Label:               componentSettings.Label,
			TwoWayStatePath:     componentSettings.TwoWayStatePath,
			Value:               componentSettings.Value,
			IsRequired:          componentSettings.IsRequired,
			IsReadOnly:          componentSettings.IsReadOnly,
			Size:                componentSettings.Size,
			TextCase:            componentSettings.TextCase,
			AffixRightComponent: passwordInputActions(
				componentSettings.ShouldShowGenerateButton,
				componentSettings.TwoWayStatePath,
				componentSettings.Size,
				componentSettings.ActionButtonStyle,
			),
			HintValue:                         componentSettings.HintValue,
			HintStatePath:                     componentSettings.HintStatePath,
			HintDisplay:                       componentSettings.HintDisplay,
			HintDisplayTooltipBackgroundColor: componentSettings.HintDisplayTooltipBackgroundColor,
			HintDisplayTooltipMinWidthClass:   componentSettings.HintDisplayTooltipMinWidthClass,
			HintDisplayTooltipMaxWidthClass:   componentSettings.HintDisplayTooltipMaxWidthClass,
			HintDisplayTooltipMinHeightClass:  componentSettings.HintDisplayTooltipMinHeightClass,
			HintDisplayTooltipMaxHeightClass:  componentSettings.HintDisplayTooltipMaxHeightClass,
			HintIconStyle:                     componentSettings.HintIconStyle,
		}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if componentSettings.ShouldShowStrengthMeter {
			strengthMeterColorClass := "bg-secondary-500"
			if componentSettings.StrengthMeterColor != "" {
				strengthMeterColorClass = "bg-" + componentSettings.StrengthMeterColor
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 7, " ")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			strengthCriteriaTextColorClass := "text-neutral-400"
			if componentSettings.StrengthCriteriaTextColor != "" {
				strengthCriteriaTextColorClass = "text-" + componentSettings.StrengthCriteriaTextColor
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 8, " ")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			strengthCriteriaFulfilledIconColorClass := "text-green-500"
			if componentSettings.StrengthCriteriaFulfilledIconColor != "" {
				strengthCriteriaFulfilledIconColorClass = "text-" + componentSettings.StrengthCriteriaFulfilledIconColor
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 9, " ")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			strengthCriteriaUnfulfilledIconColorClass := "text-red-500"
			if componentSettings.StrengthCriteriaUnfulfilledIconColor != "" {
				strengthCriteriaUnfulfilledIconColorClass = "text-" + componentSettings.StrengthCriteriaUnfulfilledIconColor
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 10, " <!-- PasswordInputStrengthMeter --> <div class=\"flex flex-col gap-1.5\"><div class=\"h-1.5 w-full overflow-hidden rounded-full bg-neutral-50/10\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var5 = []any{"h-full rounded-full transition-all duration-200 " + strengthMeterColorClass}
			templ_7745c5c3_Err = templ.RenderCSSItems(ctx, templ_7745c5c3_Buffer, templ_7745c5c3_Var5...)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 11, "<div class=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var6 string
			templ_7745c5c3_Var6, templ_7745c5c3_Err = templ.ResolveAttributeValue(templ.CSSClasses(templ_7745c5c3_Var5).String())
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `src/form/passwordInput.templ`, Line: 1, Col: 0}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var6)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 12, "\" :style=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var7 string
			templ_7745c5c3_Var7, templ_7745c5c3_Err = templ.ResolveAttributeValue("'width: ' + passwordStrengthPercentage + '%'")
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `src/form/passwordInput.templ`, Line: 306, Col: 61}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var7)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 13, "\"></div></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var8 = []any{"grid grid-cols-1 gap-x-4 gap-y-0.5 text-xs sm:grid-cols-2 " + strengthCriteriaTextColorClass}
			templ_7745c5c3_Err = templ.RenderCSSItems(ctx, templ_7745c5c3_Buffer, templ_7745c5c3_Var8...)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 14, "<ul class=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var9 string
			templ_7745c5c3_Var9, templ_7745c5c3_Err = templ.ResolveAttributeValue(templ.CSSClasses(templ_7745c5c3_Var8).String())
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `src/form/passwordInput.templ`, Line: 1, Col: 0}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var9)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 15, "\" x-show=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var10 string
			templ_7745c5c3_Var10, templ_7745c5c3_Err = templ.ResolveAttributeValue(shouldShowStrengthCriteria)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `src/form/passwordInput.templ`, Line: 309, Col: 147}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var10)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 16, "\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			for _, criteriaItem := range criteriaItems {
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 17, "<li class=\"flex items-center gap-1\">")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				var templ_7745c5c3_Var11 = []any{"ph-bold ph-check " + strengthCriteriaFulfilledIconColorClass}
				templ_7745c5c3_Err = templ.RenderCSSItems(ctx, templ_7745c5c3_Buffer, templ_7745c5c3_Var11...)
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 18, "<i class=\"")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				var templ_7745c5c3_Var12 string
				templ_7745c5c3_Var12, templ_7745c5c3_Err = templ.ResolveAttributeValue(templ.CSSClasses(templ_7745c5c3_Var11).String())
				if templ_7745c5c3_Err != nil {
					return templ.Error{Err: templ_7745c5c3_Err, FileName: `src/form/passwordInput.templ`, Line: 1, Col: 0}
				}
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var12)
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 19, "\" x-show=\"")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				var templ_7745c5c3_Var13 string
				templ_7745c5c3_Var13, templ_7745c5c3_Err = templ.ResolveAttributeValue("passwordStrengthCriteria." + criteriaItem.StateKey)
				if templ_7745c5c3_Err != nil {
					return templ.Error{Err: templ_7745c5c3_Err, FileName: `src/form/passwordInput.templ`, Line: 314, Col: 68}
				}
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var13)
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 20, "\"></i> ")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				var templ_7745c5c3_Var14 = []any{"ph-bold ph-x " + strengthCriteriaUnfulfilledIconColorClass}
				templ_7745c5c3_Err = templ.RenderCSSItems(ctx, templ_7745c5c3_Buffer, templ_7745c5c3_Var14...)
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 21, "<i class=\"")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				var templ_7745c5c3_Var15 string
				templ_7745c5c3_Var15, templ_7745c5c3_Err = templ.ResolveAttributeValue(templ.CSSClasses(templ_7745c5c3_Var14).String())
				if templ_7745c5c3_Err != nil {
					return templ.Error{Err: templ_7745c5c3_Err, FileName: `src/form/passwordInput.templ`, Line: 1, Col: 0}
				}
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var15)
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 22, "\" x-show=\"")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				var templ_7745c5c3_Var16 string
				templ_7745c5c3_Var16, templ_7745c5c3_Err = templ.ResolveAttributeValue("!passwordStrengthCriteria." + criteriaItem.StateKey)
				if templ_7745c5c3_Err != nil {
					return templ.Error{Err: templ_7745c5c3_Err, FileName: `src/form/passwordInput.templ`, Line: 318, Col: 69}
				}
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var16)
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 23, "\"></i> ")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				var templ_7745c5c3_Var17 string
				templ_7745c5c3_Var17, templ_7745c5c3_Err = templ.JoinStringErrs(criteriaItem.Label)
				if templ_7745c5c3_Err != nil {
					return templ.Error{Err: templ_7745c5c3_Err, FileName: `src/form/passwordInput.templ`, Line: 320, Col: 27}
				}
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var17))
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 24, "</li>")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 25, "</ul></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 26, "</div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
