// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1070
package uiStructural

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	uiDisplay "github.com/goinfinite/ui/src/display"
	uiToolset "github.com/goinfinite/ui/src/toolset"
)

const (
	CardShadowSizeNone string = "none"
	CardShadowSizeXs   string = "xs"
	CardShadowSizeSm   string = "sm"
	CardShadowSizeMd   string = "md"
	CardShadowSizeLg   string = "lg"
	CardShadowSizeXl   string = "xl"

	CardRingThicknessXs string = "xs"
	CardRingThicknessSm string = "sm"
	CardRingThicknessMd string = "md"
	CardRingThicknessLg string = "lg"
	CardRingThicknessXl string = "xl"

	CardPaddingSizeNone string = "none"
	CardPaddingSizeXs   string = "xs"
	CardPaddingSizeSm   string = "sm"
	CardPaddingSizeMd   string = "md"
	CardPaddingSizeLg   string = "lg"
	CardPaddingSizeXl   string = "xl"

	CardGapSizeNone string = "none"
	CardGapSizeXs   string = "xs"
	CardGapSizeSm   string = "sm"
	CardGapSizeMd   string = "md"
	CardGapSizeLg   string = "lg"
	CardGapSizeXl   string = "xl"
)

type CardSettings struct {
	MiddleContent templ.Component

	// OptionalFields
	ActionsContent                  templ.Component
	BackgroundColor                 string
	BorderRadius                    string
	FooterContent                   templ.Component
	GapSize                         string
	HeaderContent                   templ.Component
	HeaderIcon                      string
	HeaderIconBackgroundColor       string
	HeaderIconBorderRadius          string
	HeaderIconColor                 string
	HeaderIconPaddingSize           string
	HeaderIconPosition              string
	HeaderSize                      string
	HeaderSubHeading                string
	HeaderSubHeadingColor           string
	HeaderSubHeadingOneWayStatePath string
	HeaderTitle                     string
	HeaderTitleColor                string
	HeaderTitleOneWayStatePath      string
	PaddingSize                     string
	RingColor                       string
	RingThickness                   string
	ShadowSize                      string
	TextCase                        string
	TextColor                       string
}

func Card(componentSettings CardSettings) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<!-- Card -->")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		backgroundColor := uiToolset.BackgroundColorClassResolver(componentSettings.BackgroundColor, "bg-neutral-950/20")
		textColor := uiToolset.TextColorClassResolver(componentSettings.TextColor, "")
		gapClasses := uiToolset.GapClassResolver(componentSettings.GapSize, "gap-3")
		cardClasses := "flex flex-col " + gapClasses + " " + backgroundColor + " " + textColor
		cardClasses += " " + uiToolset.PaddingClassResolver(componentSettings.PaddingSize, "p-5")
		cardClasses += " " + uiToolset.BorderRadiusClassResolver(componentSettings.BorderRadius, "rounded-lg")
		cardClasses += " " + uiToolset.ShadowClassResolver(componentSettings.ShadowSize, "")
		cardClasses += " " + uiToolset.RingClassResolver(componentSettings.RingColor, componentSettings.RingThickness)
		hasHeaderBlockContent := componentSettings.HeaderTitle != "" || componentSettings.HeaderTitleOneWayStatePath != "" || componentSettings.HeaderSubHeading != "" || componentSettings.HeaderSubHeadingOneWayStatePath != "" || componentSettings.HeaderIcon != "" || componentSettings.ActionsContent != nil
		var templ_7745c5c3_Var2 = []any{cardClasses}
		templ_7745c5c3_Err = templ.RenderCSSItems(ctx, templ_7745c5c3_Buffer, templ_7745c5c3_Var2...)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<div class=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var3 string
		templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.ResolveAttributeValue(templ.CSSClasses(templ_7745c5c3_Var2).String())
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `src/structural/card.templ`, Line: 1, Col: 0}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var3)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if componentSettings.HeaderContent != nil {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "<!-- CardCustomHeader --> ")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = componentSettings.HeaderContent.Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		if componentSettings.HeaderContent == nil && hasHeaderBlockContent {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "<!-- CardHeader --> ")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = uiDisplay.HeaderBlock(uiDisplay.HeaderBlockSettings{
				ActionsContent:                  componentSettings.ActionsContent,
				HeaderIcon:                      componentSettings.HeaderIcon,
				HeaderIconBackgroundColor:       componentSettings.HeaderIconBackgroundColor,
				HeaderIconBorderRadius:          componentSettings.HeaderIconBorderRadius,
				HeaderIconColor:                 componentSettings.HeaderIconColor,
				HeaderIconPaddingSize:           componentSettings.HeaderIconPaddingSize,
				HeaderIconPosition:              componentSettings.HeaderIconPosition,
				HeaderSize:                      componentSettings.HeaderSize,
				HeaderSubHeading:                componentSettings.HeaderSubHeading,
				HeaderSubHeadingColor:           componentSettings.HeaderSubHeadingColor,
				HeaderSubHeadingOneWayStatePath: componentSettings.HeaderSubHeadingOneWayStatePath,
				HeaderTitle:                     componentSettings.HeaderTitle,
				HeaderTitleColor:                componentSettings.HeaderTitleColor,
				HeaderTitleOneWayStatePath:      componentSettings.HeaderTitleOneWayStatePath,
				HeadingLevel:                    uiDisplay.HeaderBlockHeadingLevelTwo,
				TextCase:                        componentSettings.TextCase,
			}).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, "<!-- CardMiddleContent -->")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = componentSettings.MiddleContent.Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if componentSettings.FooterContent != nil {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 7, "<!-- CardFooterContent --> ")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = componentSettings.FooterContent.Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 8, "</div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
